# Generated by Django 5.2.2 on 2025-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
