# Generated by Django 5.2.2 on 2025-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='background_image',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
