# Generated by Django 5.2.2 on 2025-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
