# Generated by Django 5.2.2 on 2025-06-18 19:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opt_in_marketing', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=50)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=50)),
                ('card_exp_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('card_exp_year', models.PositiveSmallIntegerField()),
                ('card_number', encrypted_model_fields.fields.EncryptedCharField(verbose_name=models.CharField(blank=True, max_length=16))),
                ('card_name', encrypted_model_fields.fields.EncryptedCharField(verbose_name=models.CharField(blank=True, max_length=100))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('card_exp_month__gte', 1), ('card_exp_month__lte', 12)), name='valid_exp_month'), models.CheckConstraint(condition=models.Q(('card_exp_year__gte', 2000), ('card_exp_year__lte', 2100)), name='valid_exp_year')],
            },
        ),
    ]
