# Generated by Django 5.2.2 on 2025-06-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_billing_cycle_alter_order_plan_id_and_more'),
        ('shop', '0018_remove_order_billing_address_billingaddress_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
