# Generated by Django 5.2.2 on 2025-06-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='orders',
        ),
    ]
