# Generated by Django 5.2.2 on 2025-06-20 20:40

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_order_order_orders'),
        ('shop', '0018_remove_order_billing_address_billingaddress_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savedpaymentmethod',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Saved Payment Method', 'verbose_name_plural': 'Saved Payment Methods'},
        ),
        migrations.RemoveConstraint(
            model_name='savedpaymentmethod',
            name='valid_exp_month',
        ),
        migrations.RemoveConstraint(
            model_name='savedpaymentmethod',
            name='valid_exp_year',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan_name',
        ),
        migrations.AddField(
            model_name='order',
            name='shop_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('requires_action', 'Requires Action')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='card_exp_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='card_exp_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='card_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
    ]
