# Generated by Django 5.2.2 on 2025-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='percentage_discount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_before_discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
