# Generated by Django 5.2.2 on 2025-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_slug_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-products', unique=True),
        ),
    ]
