# Generated by Django 5.2.2 on 2025-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='This is test description for items', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, default=4.6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('E', 'extra_large')], default='M', max_length=2),
        ),
    ]
