# Generated by Django 5.2.2 on 2025-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_method',
            field=models.CharField(default='stripe', max_length=50),
        ),
    ]
