# Generated by Django 5.2.2 on 2025-06-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_total_order_total_before_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
