# Generated by Django 5.2.2 on 2025-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_customer_customertestimonials_item_item_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertestimonials',
            name='customer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/customerAvatar'),
        ),
        migrations.AddField(
            model_name='customertestimonials',
            name='customer_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customertestimonials',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customertestimonials',
            name='customer_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customertestimonials',
            name='customer_testimony',
            field=models.TextField(blank=True, null=True),
        ),
    ]
