# Generated by Django 5.2.2 on 2025-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_customertestimonials_customer_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertestimonials',
            name='customer_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
