# Generated by Django 5.2.2 on 2025-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_customertestimonials_customer_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertestimonials',
            name='customer_position',
            field=models.CharField(default='customer', max_length=50),
        ),
    ]
