# Generated by Django 5.2.2 on 2025-06-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_wishlist_ordered_wishlist_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
