# Generated by Django 5.2.3 on 2025-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
