# Generated by Django 5.2.3 on 2025-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-products', unique=True),
        ),
    ]
