# Generated by Django 5.2.3 on 2025-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_item_name_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, default='test-products', null=True, unique=True),
        ),
    ]
